spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '{cipher}AQAMgqMfj1finDeqcNX7jwWhudHbUrbR5+n1pwkIoDbfPAZdIqyXDqKYkT3zFI3nVcVX00RJFfOZi9q53aAuZkn7Hp5AhqWAv7vQyzeBipgQ1lm1sBQutz+RCti87gv7+TOhi0hZtG7oJ/dxtlz7tlUVILL4mj9xdsADf69q4Lh5xCdMoWB6PPTf0lGkxMgz3yZQX0+9f5DZ+M80wiNGkGDvhatSvADsV5ImekFhX1xMbP66fJkZmLkiyyApyxsrxUtvD8oj531asvsYVAvxAxWxe59yZ05F3f486bcuMxW7OJcAHyny4sau8Tx2coeSVY5djrLSqOyZPzBid2XK2jSI+wWsWRkef4ycVuqgTgr2XqbswFS9Hqil842TTkQwQs4='
    url: jdbc:mysql://vcomsmb20.iptime.org:18306/msa-user?characterEncoding=UTF-8&serverTimezone=UTC
    username: unismb

token:
  expiration_accessToken_time: 86400000
  expiration_refreshToken_time: 1209600000
  secret: '{cipher}AQAZxJvbr62UH5QR8Rk1jzI2RyfWaCw4JVSqe9wZgAnJsg/OQzcgFTbqqfXJLn1PI6XElud1UvIodoytFoU4vTtahsy/NLst6x67AqeMX701lmEGo0BL5ZVPC+q2Uzm3+OaUr8/Ke+OzPk4P0WlGGdgNUqqHLxhMxNQlLVrUPIOKj7H02bmG43Yn7/ZIm2NOYHE9GZjp6J8nduHkn9o7NjYGwOo/ESMNAYL68hCy5ElpDIXGl5SyoJEiLD/Wshie3a64yv6qZ1C95Ko0781WQTHzd+bF8g8Lq1K2Pw4jE8eDUyur5vn9y9mK9rmvs4vvQu4u/sZa8wxdUbt5TurHjcD0OKDk9efnUiRTvTmeVMEPXGoeSnzERx4g8dnBIoPDDK6ZBMpk0Djw1B7tsSI5AqAiYMi9eD6Cp1kx87Zf+31Ekk0PPNh2+T2ePPnQXQu71U31kyv0o3eezruxsGql1/gJqyrLzlXIG9ayBV5g593M5w=='

gateway:
  ip: 127.0.0.1

order_service:
  url: http://127.0.0.1:8000/order-service/%s/orders